LANGUAGE_FLAGS_MAP = {
  "en": "gb",
  "id": "id",
  "ja": "jp",
  "ko": "kr",
  "pt-br": "br",
  "th": "th",
  "tr": "tr",
  "vi": "vn",
  "zh": "cn",
  "zh-cn": "cn",
  "zh-hans": "cn",
  "zh-hans-hk": "hk",
  "zh-hans-tw": "tw",
  "zh-hant": "tw",
  "zh-hant-hk": "hk",
  "zh-hant-tw": "tw",
  "zh-hk": "hk",
  "zh-mo": "mo",
  "zh-sg": "sg",
  "zh-tw": "tw",
}

GENRES_MAP = {
  "지금 핫한": "🔥",
  "판타지 드라마": "Fantasy Drama",
  "로맨스": "Romance",
  "학원/판타지": "School/Fantasy",
  "로맨스 판타지": "Romance Fantasy",
  "액션/무협": "Action/Martial Arts",
  "드라마": "Drama",
  "공포/스릴러": "Horror/Thriller",
  "코믹/일상": "Comic/Daily Life",
}
