name: cog-coffeeani

on:
  push:
    branches:
      - master
    paths:
      - 'coffeeani/**'

jobs:
  build-dpy:
    uses: coffeebank/coffee-cogs/.github/workflows/build-dpy.yml@docs/dpy
    with:
      COG_NAME: coffeeani
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
